// swift-tools-version: 6.0.0
// AUTO-GENERATED by swift-binify - Prebuilt binary package
import PackageDescription

let package = Package(
    name: "swiftui-introspect",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13)],
    products: [
        .library(name: "SwiftUIIntrospect", targets: ["SwiftUIIntrospect"]),
        .library(name: "SwiftUIIntrospect-Dynamic", targets: ["SwiftUIIntrospect"])
    ],
    targets: [
        .binaryTarget(
            name: "SwiftUIIntrospect",
            url: "https://github.com/swift-bins/SwiftUI-Introspect/releases/download/26.0.0/SwiftUIIntrospect.xcframework.zip",
            checksum: "ad7dd1c6dabf647f210c948b26c8fc932d80b45c2ed475d17de04e8119de949a"
        )
    ]
)
