// swift-tools-version: 6.0.0
// AUTO-GENERATED by swift-binify - Prebuilt binary package
import PackageDescription

let package = Package(
    name: "swiftui-introspect",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13)],
    products: [
        .library(name: "SwiftUIIntrospect", targets: ["SwiftUIIntrospect"]),
        .library(name: "SwiftUIIntrospect-Dynamic", targets: ["SwiftUIIntrospect"])
    ],
    targets: [
        .binaryTarget(
            name: "SwiftUIIntrospect",
            url: "https://github.com/swift-bins/SwiftUI-Introspect/releases/download/26.0.0/SwiftUIIntrospect.xcframework.zip",
            checksum: "d779fb62e65e64a36436b8f502b53243a9addaa379e89f6e007ba2203fd50c32"
        )
    ]
)
